name: poploda
server_host: localhost
server_port: 8888
sub_domain: push
secret: secret
domain: push.rzaartz.local
env: development
db: /Users/charlesokwandu/desktop/project/poploda/config/
log_path: /Users/charlesokwandu/desktop/poploda_service/log